# Generated by sila2.code_generator; sila2.__version__: 0.12.2
from __future__ import annotations

import logging
import time
from datetime import timedelta
from threading import Thread, Lock
from typing import TYPE_CHECKING, Optional, Union

from sila2.server import MetadataDict, ObservableCommandInstance

from vspin_driver.centrifuge_api import VSpinCentrifuge, VSpinLoader, LoaderNoPlateError, LoaderStageOccupiedError

from ..generated.vspincontroller import (
    DeviceNotInitialized,
    NoPlateDetected,
    StageOccupied,
    VSpinControllerBase,
    CloseDoor_Responses,
    CloseGripper_Responses,
    GoToBucket1_Responses,
    GoToBucket2_Responses,
    GoToTeachpoint_Responses,
    Load_Responses,
    LockBucket_Responses,
    LockDoor_Responses,
    OpenDoor_Responses,
    OpenGripper_Responses,
    StartSpin_Responses,
    Unload_Responses,
    UnlockBucket_Responses,
    UnlockDoor_Responses,
)

if TYPE_CHECKING:
    from ..server import Server

class VSpinControllerImpl(VSpinControllerBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Get device connection parameters from the parent server
        self.centrifuge_port = self.parent_server.centrifuge_com_port
        self.loader_port = self.parent_server.loader_com_port
        self.calibration_offset = self.parent_server.calibration_offset

        self.centrifuge: Optional[VSpinCentrifuge] = None
        self.loader: Optional[VSpinLoader] = None
        self.is_running = True
        
        self.device_lock = Lock()

    def start(self) -> None:
        logging.info("VSpinController feature starting...")
        self.update_CentrifugeStatus("Initializing")
        try:
            self.centrifuge = VSpinCentrifuge(port=self.centrifuge_port, calibration_offset=self.calibration_offset)
            self.loader = VSpinLoader(port=self.loader_port)
            
            with self.device_lock:
                self.loader.initialize()
                self.centrifuge.initialize()

            self.is_running = True
            self.property_updater_thread = Thread(target=self._update_properties, daemon=True)
            self.property_updater_thread.start()

            self.update_CentrifugeStatus("Idle")
            logging.info("VSpinController feature started successfully.")
        except Exception as e:
            logging.error(f"Failed to initialize devices: {e}")
            self.update_CentrifugeStatus("Error")
            raise
        super().start()

    def stop(self) -> None:
        logging.info("VSpinController feature stopping...")
        self.is_running = False
        if hasattr(self, 'property_updater_thread') and self.property_updater_thread.is_alive():
            self.property_updater_thread.join(timeout=2)

        with self.device_lock:
            if self.loader:
                self.loader.close()
            if self.centrifuge:
                self.centrifuge.close()
                
        logging.info("VSpinController feature stopped.")
        super().stop()

    def _update_properties(self) -> None:
        while self.is_running:
            with self.device_lock:
                try:
                    if self.centrifuge and self.centrifuge._is_initialized:
                        door_status = self.centrifuge.get_door_status()
                        self.update_DoorStatus(door_status)
                        rotor_pos = self.centrifuge._get_position()
                        if rotor_pos is not None:
                            self.update_RotorPosition(rotor_pos)

                    if self.loader and self.loader._is_initialized:
                        try:
                            self.loader.check_for_plate()
                            self.update_IsPlateInGripper(True)
                        except LoaderNoPlateError:
                            self.update_IsPlateInGripper(False)
                        except Exception as e:
                            pass

                except Exception as e:
                    logging.error(f"Error during property update poll: {e}")
                    self.update_CentrifugeStatus("Error")
            
            time.sleep(1)

    def _check_initialized(self):
        if not (self.centrifuge and self.centrifuge._is_initialized and self.loader and self.loader._is_initialized):
            raise DeviceNotInitialized("The device has not been initialized.")

    def OpenGripper(self, *, metadata: MetadataDict) -> OpenGripper_Responses:
        self._check_initialized()
        with self.device_lock:
            self.loader._open_gripper()
        return OpenGripper_Responses()

    def CloseGripper(self, IsGentle: bool, *, metadata: MetadataDict) -> CloseGripper_Responses:
        self._check_initialized()
        with self.device_lock:
            self.loader._close_gripper(is_gentle=IsGentle)
        return CloseGripper_Responses()

    def OpenDoor(self, *, metadata: MetadataDict) -> OpenDoor_Responses:
        self._check_initialized()
        with self.device_lock:
            self.centrifuge.open_door()
        return OpenDoor_Responses()

    def CloseDoor(self, *, metadata: MetadataDict) -> CloseDoor_Responses:
        self._check_initialized()
        with self.device_lock:
            self.centrifuge.close_door()
        return CloseDoor_Responses()

    def LockDoor(self, *, metadata: MetadataDict) -> LockDoor_Responses:
        self._check_initialized()
        with self.device_lock:
            self.centrifuge.lock_door()
        return LockDoor_Responses()

    def UnlockDoor(self, *, metadata: MetadataDict) -> UnlockDoor_Responses:
        self._check_initialized()
        with self.device_lock:
            self.centrifuge.unlock_door()
        return UnlockDoor_Responses()

    def LockBucket(self, *, metadata: MetadataDict) -> LockBucket_Responses:
        self._check_initialized()
        with self.device_lock:
            self.centrifuge.lock_bucket()
        return LockBucket_Responses()

    def UnlockBucket(self, *, metadata: MetadataDict) -> UnlockBucket_Responses:
        self._check_initialized()
        with self.device_lock:
            self.centrifuge.unlock_bucket()
        return UnlockBucket_Responses()

    def StartSpin(
        self,
        GForce: float,
        Duration: int,
        Acceleration: float,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> StartSpin_Responses:
        self._check_initialized()
        instance.begin_execution()

        with self.device_lock:
            try:
                self.update_CentrifugeStatus("Spinning")
                instance.progress = 0
                total_duration = Duration + 20 
                instance.estimated_remaining_time = timedelta(seconds=total_duration)

                self.centrifuge.start_spin(
                    g_force=GForce, duration_s=Duration, acceleration_percent=Acceleration
                )

                instance.progress = 1
                self.update_CentrifugeStatus("Idle")
                return StartSpin_Responses()

            except Exception as e:
                self.update_CentrifugeStatus("Error")
                logging.error(f"Error during StartSpin: {e}")
                raise 

    def Load(
        self,
        BucketNumber: int,
        GripperZOffset: float,
        PlateHeight: float,
        Speed: str,
        IsGentle: bool,
        IgnorePlateSensor: bool,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Load_Responses:
        self._check_initialized()
        instance.begin_execution()

        with self.device_lock:
            try:
                self.update_CentrifugeStatus("Loading")
                
                options = 0
                if IsGentle: options |= self.loader.OPTIONS_BITMASK["Grip Gently"]
                if IgnorePlateSensor: options |= self.loader.OPTIONS_BITMASK["Ignore Plate Sensor"]

                instance.progress = 0.1
                self.loader.load(
                    bucket_number=BucketNumber,
                    gripper_z_offset=GripperZOffset,
                    plate_height=PlateHeight,
                    speed_name=Speed,
                    options=options
                )
                
                instance.progress = 1
                self.update_CentrifugeStatus("Idle")
                return Load_Responses()

            except LoaderNoPlateError as e:
                self.update_CentrifugeStatus("Error")
                raise NoPlateDetected(str(e))
            except Exception as e:
                self.update_CentrifugeStatus("Error")
                raise

    def Unload(
        self,
        BucketNumber: int,
        GripperZOffset: float,
        PlateHeight: float,
        Speed: str,
        IsGentle: bool,
        IgnorePlateSensor: bool,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> Unload_Responses:
        self._check_initialized()
        instance.begin_execution()

        with self.device_lock:
            try:
                self.update_CentrifugeStatus("Unloading")
                instance.progress = 0.1
                
                options = 0
                if IsGentle: options |= self.loader.OPTIONS_BITMASK["Grip Gently"]
                if IgnorePlateSensor: options |= self.loader.OPTIONS_BITMASK["Ignore Plate Sensor"]

                self.loader.unload(
                    bucket_number=BucketNumber,
                    gripper_z_offset=GripperZOffset,
                    plate_height=PlateHeight,
                    speed_name=Speed,
                    options=options
                )
                instance.progress = 1
                self.update_CentrifugeStatus("Idle")
                return Unload_Responses()

            except LoaderNoPlateError as e:
                self.update_CentrifugeStatus("Error")
                raise NoPlateDetected(str(e))
            except LoaderStageOccupiedError as e:
                self.update_CentrifugeStatus("Error")
                raise StageOccupied(str(e))
            except Exception as e:
                self.update_CentrifugeStatus("Error")
                raise

    def GoToTeachpoint(
        self,
        TeachpointName: str,
        GripperZOffset: float,
        PlateHeight: float,
        Speed: str,
        *,
        metadata: MetadataDict,
        instance: ObservableCommandInstance,
    ) -> GoToTeachpoint_Responses:
        self._check_initialized()
        instance.begin_execution()
        
        with self.device_lock:
            self.update_CentrifugeStatus("Moving")
            self.loader.go_to_teachpoint(
                teachpoint_name=TeachpointName,
                gripper_z_offset=GripperZOffset,
                plate_height=PlateHeight,
                speed_name=Speed
            )
            self.update_CentrifugeStatus("Idle")
            
        return GoToTeachpoint_Responses()

    def GoToBucket1(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> GoToBucket1_Responses:
        self._check_initialized()
        instance.begin_execution()
        
        with self.device_lock:
            self.update_CentrifugeStatus("Moving")
            self.centrifuge.go_to_bucket1()
            self.update_CentrifugeStatus("Idle")

        return GoToBucket1_Responses()

    def GoToBucket2(self, *, metadata: MetadataDict, instance: ObservableCommandInstance) -> GoToBucket2_Responses:
        self._check_initialized()
        instance.begin_execution()
        
        with self.device_lock:
            self.update_CentrifugeStatus("Moving")
            self.centrifuge.go_to_bucket2()
            self.update_CentrifugeStatus("Idle")
            
        return GoToBucket2_Responses()